import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-ovo',
});

export const metadata = {
  title: "Portfolio - Mir Tariquddin",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/profile-img.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${ovo.className} antialiased leading-8
        overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
